-- SQL pour corriger les chemins WebP

UPDATE products SET image = 'images/uploads/a-cr-pe-1a0f8d8b.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/a-cr-pe-1a0f8d8b.png', 'images/uploads/a-cr-pe-1a0f8d8b.jpg', 'images/uploads/a-cr-pe-1a0f8d8b.jpeg');
UPDATE products SET image = 'images/uploads/acos-628ae502.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/acos-628ae502.png', 'images/uploads/acos-628ae502.jpg', 'images/uploads/acos-628ae502.jpeg');
UPDATE products SET image = 'images/uploads/ain-epice-259f2e72.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/ain-epice-259f2e72.png', 'images/uploads/ain-epice-259f2e72.jpg', 'images/uploads/ain-epice-259f2e72.jpeg');
UPDATE products SET image = 'images/uploads/arguerita-2b799090.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/arguerita-2b799090.png', 'images/uploads/arguerita-2b799090.jpg', 'images/uploads/arguerita-2b799090.jpeg');
UPDATE products SET image = 'images/uploads/auffre-compliqu-b6efb3af.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/auffre-compliqu-b6efb3af.png', 'images/uploads/auffre-compliqu-b6efb3af.jpg', 'images/uploads/auffre-compliqu-b6efb3af.jpeg');
UPDATE products SET image = 'images/uploads/croque-monsieur-82c66930.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/croque-monsieur-82c66930.png', 'images/uploads/croque-monsieur-82c66930.jpg', 'images/uploads/croque-monsieur-82c66930.jpeg');
UPDATE products SET image = 'images/uploads/e-fabrik-a229a7c4.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/e-fabrik-a229a7c4.png', 'images/uploads/e-fabrik-a229a7c4.jpg', 'images/uploads/e-fabrik-a229a7c4.jpeg');
UPDATE products SET image = 'images/uploads/e-walou-0cd58c19.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/e-walou-0cd58c19.png', 'images/uploads/e-walou-0cd58c19.jpg', 'images/uploads/e-walou-0cd58c19.jpeg');
UPDATE products SET image = 'images/uploads/fromagere-443e8930.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/fromagere-443e8930.png', 'images/uploads/fromagere-443e8930.jpg', 'images/uploads/fromagere-443e8930.jpeg');
UPDATE products SET image = 'images/uploads/g-ahal-5f82693a.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/g-ahal-5f82693a.png', 'images/uploads/g-ahal-5f82693a.jpg', 'images/uploads/g-ahal-5f82693a.jpeg');
UPDATE products SET image = 'images/uploads/hakhchoukha-1c5ca555.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/hakhchoukha-1c5ca555.png', 'images/uploads/hakhchoukha-1c5ca555.jpg', 'images/uploads/hakhchoukha-1c5ca555.jpeg');
UPDATE products SET image = 'images/uploads/lyonnaise-41dff609.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/lyonnaise-41dff609.png', 'images/uploads/lyonnaise-41dff609.jpg', 'images/uploads/lyonnaise-41dff609.jpeg');
UPDATE products SET image = 'images/uploads/lyonnaise-ab342664.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/lyonnaise-ab342664.png', 'images/uploads/lyonnaise-ab342664.jpg', 'images/uploads/lyonnaise-ab342664.jpeg');
UPDATE products SET image = 'images/uploads/lyonnaise-b5db6249.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/lyonnaise-b5db6249.png', 'images/uploads/lyonnaise-b5db6249.jpg', 'images/uploads/lyonnaise-b5db6249.jpeg');
UPDATE products SET image = 'images/uploads/parisienne-f822547f.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/parisienne-f822547f.png', 'images/uploads/parisienne-f822547f.jpg', 'images/uploads/parisienne-f822547f.jpeg');
UPDATE products SET image = 'images/uploads/pat-cheesecake-104d5b3d.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/pat-cheesecake-104d5b3d.png', 'images/uploads/pat-cheesecake-104d5b3d.jpg', 'images/uploads/pat-cheesecake-104d5b3d.jpeg');
UPDATE products SET image = 'images/uploads/pat-flan-4dc6c276.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/pat-flan-4dc6c276.png', 'images/uploads/pat-flan-4dc6c276.jpg', 'images/uploads/pat-flan-4dc6c276.jpeg');
UPDATE products SET image = 'images/uploads/pat-tiramisu-99367150.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/pat-tiramisu-99367150.png', 'images/uploads/pat-tiramisu-99367150.jpg', 'images/uploads/pat-tiramisu-99367150.jpeg');
UPDATE products SET image = 'images/uploads/poiu-93020e44.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/poiu-93020e44.png', 'images/uploads/poiu-93020e44.jpg', 'images/uploads/poiu-93020e44.jpeg');
UPDATE products SET image = 'images/uploads/ptit-dej-f6a3e393.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/ptit-dej-f6a3e393.png', 'images/uploads/ptit-dej-f6a3e393.jpg', 'images/uploads/ptit-dej-f6a3e393.jpeg');
UPDATE products SET image = 'images/uploads/repe-burger-01c05667.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/repe-burger-01c05667.png', 'images/uploads/repe-burger-01c05667.jpg', 'images/uploads/repe-burger-01c05667.jpeg');
UPDATE products SET image = 'images/uploads/rousty-7406eb2b.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/rousty-7406eb2b.png', 'images/uploads/rousty-7406eb2b.jpg', 'images/uploads/rousty-7406eb2b.jpeg');
UPDATE products SET image = 'images/uploads/saumon-188ad6b4.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/saumon-188ad6b4.png', 'images/uploads/saumon-188ad6b4.jpg', 'images/uploads/saumon-188ad6b4.jpeg');
UPDATE products SET image = 'images/uploads/urgers-cfce7857.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/urgers-cfce7857.png', 'images/uploads/urgers-cfce7857.jpg', 'images/uploads/urgers-cfce7857.jpeg');
UPDATE products SET image = 'images/uploads/viennoiseries-1a242d05.webp' WHERE restaurant_id = 2 AND image IN ('images/uploads/viennoiseries-1a242d05.png', 'images/uploads/viennoiseries-1a242d05.jpg', 'images/uploads/viennoiseries-1a242d05.jpeg');

-- Fin des mises à jour
